# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/julien/Projects/cfreecell

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/julien/Projects/cfreecell

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/julien/Projects/cfreecell/CMakeFiles /home/julien/Projects/cfreecell/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/julien/Projects/cfreecell/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named freecell

# Build rule for target.
freecell: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 freecell
.PHONY : freecell

# fast build rule for target.
freecell/fast:
	$(MAKE) -f CMakeFiles/freecell.dir/build.make CMakeFiles/freecell.dir/build
.PHONY : freecell/fast

src/array.o: src/array.c.o

.PHONY : src/array.o

# target to build an object file
src/array.c.o:
	$(MAKE) -f CMakeFiles/freecell.dir/build.make CMakeFiles/freecell.dir/src/array.c.o
.PHONY : src/array.c.o

src/array.i: src/array.c.i

.PHONY : src/array.i

# target to preprocess a source file
src/array.c.i:
	$(MAKE) -f CMakeFiles/freecell.dir/build.make CMakeFiles/freecell.dir/src/array.c.i
.PHONY : src/array.c.i

src/array.s: src/array.c.s

.PHONY : src/array.s

# target to generate assembly for a file
src/array.c.s:
	$(MAKE) -f CMakeFiles/freecell.dir/build.make CMakeFiles/freecell.dir/src/array.c.s
.PHONY : src/array.c.s

src/board.o: src/board.c.o

.PHONY : src/board.o

# target to build an object file
src/board.c.o:
	$(MAKE) -f CMakeFiles/freecell.dir/build.make CMakeFiles/freecell.dir/src/board.c.o
.PHONY : src/board.c.o

src/board.i: src/board.c.i

.PHONY : src/board.i

# target to preprocess a source file
src/board.c.i:
	$(MAKE) -f CMakeFiles/freecell.dir/build.make CMakeFiles/freecell.dir/src/board.c.i
.PHONY : src/board.c.i

src/board.s: src/board.c.s

.PHONY : src/board.s

# target to generate assembly for a file
src/board.c.s:
	$(MAKE) -f CMakeFiles/freecell.dir/build.make CMakeFiles/freecell.dir/src/board.c.s
.PHONY : src/board.c.s

src/common.o: src/common.c.o

.PHONY : src/common.o

# target to build an object file
src/common.c.o:
	$(MAKE) -f CMakeFiles/freecell.dir/build.make CMakeFiles/freecell.dir/src/common.c.o
.PHONY : src/common.c.o

src/common.i: src/common.c.i

.PHONY : src/common.i

# target to preprocess a source file
src/common.c.i:
	$(MAKE) -f CMakeFiles/freecell.dir/build.make CMakeFiles/freecell.dir/src/common.c.i
.PHONY : src/common.c.i

src/common.s: src/common.c.s

.PHONY : src/common.s

# target to generate assembly for a file
src/common.c.s:
	$(MAKE) -f CMakeFiles/freecell.dir/build.make CMakeFiles/freecell.dir/src/common.c.s
.PHONY : src/common.c.s

src/freecell.o: src/freecell.c.o

.PHONY : src/freecell.o

# target to build an object file
src/freecell.c.o:
	$(MAKE) -f CMakeFiles/freecell.dir/build.make CMakeFiles/freecell.dir/src/freecell.c.o
.PHONY : src/freecell.c.o

src/freecell.i: src/freecell.c.i

.PHONY : src/freecell.i

# target to preprocess a source file
src/freecell.c.i:
	$(MAKE) -f CMakeFiles/freecell.dir/build.make CMakeFiles/freecell.dir/src/freecell.c.i
.PHONY : src/freecell.c.i

src/freecell.s: src/freecell.c.s

.PHONY : src/freecell.s

# target to generate assembly for a file
src/freecell.c.s:
	$(MAKE) -f CMakeFiles/freecell.dir/build.make CMakeFiles/freecell.dir/src/freecell.c.s
.PHONY : src/freecell.c.s

src/hashset.o: src/hashset.c.o

.PHONY : src/hashset.o

# target to build an object file
src/hashset.c.o:
	$(MAKE) -f CMakeFiles/freecell.dir/build.make CMakeFiles/freecell.dir/src/hashset.c.o
.PHONY : src/hashset.c.o

src/hashset.i: src/hashset.c.i

.PHONY : src/hashset.i

# target to preprocess a source file
src/hashset.c.i:
	$(MAKE) -f CMakeFiles/freecell.dir/build.make CMakeFiles/freecell.dir/src/hashset.c.i
.PHONY : src/hashset.c.i

src/hashset.s: src/hashset.c.s

.PHONY : src/hashset.s

# target to generate assembly for a file
src/hashset.c.s:
	$(MAKE) -f CMakeFiles/freecell.dir/build.make CMakeFiles/freecell.dir/src/hashset.c.s
.PHONY : src/hashset.c.s

src/hashtable.o: src/hashtable.c.o

.PHONY : src/hashtable.o

# target to build an object file
src/hashtable.c.o:
	$(MAKE) -f CMakeFiles/freecell.dir/build.make CMakeFiles/freecell.dir/src/hashtable.c.o
.PHONY : src/hashtable.c.o

src/hashtable.i: src/hashtable.c.i

.PHONY : src/hashtable.i

# target to preprocess a source file
src/hashtable.c.i:
	$(MAKE) -f CMakeFiles/freecell.dir/build.make CMakeFiles/freecell.dir/src/hashtable.c.i
.PHONY : src/hashtable.c.i

src/hashtable.s: src/hashtable.c.s

.PHONY : src/hashtable.s

# target to generate assembly for a file
src/hashtable.c.s:
	$(MAKE) -f CMakeFiles/freecell.dir/build.make CMakeFiles/freecell.dir/src/hashtable.c.s
.PHONY : src/hashtable.c.s

src/isort.o: src/isort.c.o

.PHONY : src/isort.o

# target to build an object file
src/isort.c.o:
	$(MAKE) -f CMakeFiles/freecell.dir/build.make CMakeFiles/freecell.dir/src/isort.c.o
.PHONY : src/isort.c.o

src/isort.i: src/isort.c.i

.PHONY : src/isort.i

# target to preprocess a source file
src/isort.c.i:
	$(MAKE) -f CMakeFiles/freecell.dir/build.make CMakeFiles/freecell.dir/src/isort.c.i
.PHONY : src/isort.c.i

src/isort.s: src/isort.c.s

.PHONY : src/isort.s

# target to generate assembly for a file
src/isort.c.s:
	$(MAKE) -f CMakeFiles/freecell.dir/build.make CMakeFiles/freecell.dir/src/isort.c.s
.PHONY : src/isort.c.s

src/stack.o: src/stack.c.o

.PHONY : src/stack.o

# target to build an object file
src/stack.c.o:
	$(MAKE) -f CMakeFiles/freecell.dir/build.make CMakeFiles/freecell.dir/src/stack.c.o
.PHONY : src/stack.c.o

src/stack.i: src/stack.c.i

.PHONY : src/stack.i

# target to preprocess a source file
src/stack.c.i:
	$(MAKE) -f CMakeFiles/freecell.dir/build.make CMakeFiles/freecell.dir/src/stack.c.i
.PHONY : src/stack.c.i

src/stack.s: src/stack.c.s

.PHONY : src/stack.s

# target to generate assembly for a file
src/stack.c.s:
	$(MAKE) -f CMakeFiles/freecell.dir/build.make CMakeFiles/freecell.dir/src/stack.c.s
.PHONY : src/stack.c.s

src/strategy.o: src/strategy.c.o

.PHONY : src/strategy.o

# target to build an object file
src/strategy.c.o:
	$(MAKE) -f CMakeFiles/freecell.dir/build.make CMakeFiles/freecell.dir/src/strategy.c.o
.PHONY : src/strategy.c.o

src/strategy.i: src/strategy.c.i

.PHONY : src/strategy.i

# target to preprocess a source file
src/strategy.c.i:
	$(MAKE) -f CMakeFiles/freecell.dir/build.make CMakeFiles/freecell.dir/src/strategy.c.i
.PHONY : src/strategy.c.i

src/strategy.s: src/strategy.c.s

.PHONY : src/strategy.s

# target to generate assembly for a file
src/strategy.c.s:
	$(MAKE) -f CMakeFiles/freecell.dir/build.make CMakeFiles/freecell.dir/src/strategy.c.s
.PHONY : src/strategy.c.s

src/xxhash.o: src/xxhash.c.o

.PHONY : src/xxhash.o

# target to build an object file
src/xxhash.c.o:
	$(MAKE) -f CMakeFiles/freecell.dir/build.make CMakeFiles/freecell.dir/src/xxhash.c.o
.PHONY : src/xxhash.c.o

src/xxhash.i: src/xxhash.c.i

.PHONY : src/xxhash.i

# target to preprocess a source file
src/xxhash.c.i:
	$(MAKE) -f CMakeFiles/freecell.dir/build.make CMakeFiles/freecell.dir/src/xxhash.c.i
.PHONY : src/xxhash.c.i

src/xxhash.s: src/xxhash.c.s

.PHONY : src/xxhash.s

# target to generate assembly for a file
src/xxhash.c.s:
	$(MAKE) -f CMakeFiles/freecell.dir/build.make CMakeFiles/freecell.dir/src/xxhash.c.s
.PHONY : src/xxhash.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... freecell"
	@echo "... src/array.o"
	@echo "... src/array.i"
	@echo "... src/array.s"
	@echo "... src/board.o"
	@echo "... src/board.i"
	@echo "... src/board.s"
	@echo "... src/common.o"
	@echo "... src/common.i"
	@echo "... src/common.s"
	@echo "... src/freecell.o"
	@echo "... src/freecell.i"
	@echo "... src/freecell.s"
	@echo "... src/hashset.o"
	@echo "... src/hashset.i"
	@echo "... src/hashset.s"
	@echo "... src/hashtable.o"
	@echo "... src/hashtable.i"
	@echo "... src/hashtable.s"
	@echo "... src/isort.o"
	@echo "... src/isort.i"
	@echo "... src/isort.s"
	@echo "... src/stack.o"
	@echo "... src/stack.i"
	@echo "... src/stack.s"
	@echo "... src/strategy.o"
	@echo "... src/strategy.i"
	@echo "... src/strategy.s"
	@echo "... src/xxhash.o"
	@echo "... src/xxhash.i"
	@echo "... src/xxhash.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

